[package]
name = "wei-tray"
version = "0.1.0"
edition = "2021"
description = "wei tray"
documentation = "https://github.com/zuiyue-com/wei-tray"
homepage = "https://github.com/zuiyue-com/wei-tray"
license = "MIT OR Apache-2.0"

[dependencies]
systray = "0.4.0"
webbrowser = "0.8.10"
wei-env = "0.1.0"